# Generated by Django 4.0.1 on 2022-06-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default='pending', max_length=255)),
                ('quantity_pledged', models.IntegerField(default=0)),
                ('quantity_redeemed', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonetaryPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default='pending', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_pledged', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMonetaryPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default='pending', max_length=255)),
                ('amount_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_pledged', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pledge_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberItemPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default='pending', max_length=255)),
                ('quantity_pledged', models.IntegerField(default=0)),
                ('quantity_redeemed', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=255)),
                ('pledge_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
