# Generated by Django 4.0.1 on 2022-06-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='muid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
