# Generated by Django 4.0.1 on 2022-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_muid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='muid',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
    ]
