# Generated by Django 4.0.1 on 2022-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_member_muid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='muid',
            field=models.CharField(default='123456789012', max_length=12),
            preserve_default=False,
        ),
    ]
