# Generated by Django 4.0.1 on 2022-06-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_organisation_description_group_description_and_more'),
        ('membership', '0007_alter_member_muid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='muid',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='groups', to='groups.Group'),
        ),
    ]
