# Generated by Django 4.0.1 on 2022-06-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_member_muid_alter_member_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_ccv', to='membership.member'),
        ),
    ]
