# Generated by Django 4.0.1 on 2022-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_memberreligiouscv_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberreligiouscv',
            name='holy_matrimony_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberreligiouscv',
            name='holy_matrimony_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberreligiouscv',
            name='holy_matrimony_presided_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberreligiouscv',
            name='holy_matrimony_status',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=True),
        ),
    ]
