# Generated by Django 4.0.1 on 2022-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_memberreligiouscv_holy_matrimony_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='baptism_status',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=None),
        ),
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='confirmation_status',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=None),
        ),
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='holy_communion_status',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=None),
        ),
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='holy_matrimony_status',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=None),
        ),
    ]
