# Generated by Django 4.0.1 on 2022-06-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_member_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('not-applicable', 'Not Applicable'), ('unemployed', 'Unemployed'), ('self-employed', 'Self-Employed'), ('employed', 'Employed')], default=None, max_length=255, null=True),
        ),
    ]
