# Generated by Django 4.0.1 on 2022-06-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
