# Generated by Django 4.0.1 on 2022-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraccount_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(default='default_profile_photo.jpg', upload_to='user_profile_photos'),
        ),
    ]
