# Generated by Django 4.0.1 on 2022-06-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levy', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
        migrations.AlterUniqueTogether(
            name='levy',
            unique_together={('year', 'month')},
        ),
    ]
